language: java
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: lookatme12321313
env:
  global: cJwDcMoll7y+ko3JvjW/AfX0BnwI7F/OSjZW3XxZmWpcggjqPgF8FszT7NGuJD/6Up5cUQXdWzAHR71g8SbvvRGfMe+Oz6ZaGmH+1cObh90B4sG3LXzh9WtG2sUlZMe8hUKBgcBSlihd4SfWdMW8KQ2+TSGPwRHFJUIMz7sumutsecfnnwVWZzfXRh5H7UBUx2xmdi+2JfbGOsuk5+hgtCq0AP7/l9fPUfXxZNSlUbwjJDL6r1wHUSBNlzNUp3o2JCsZnomAwkb2m4qjVG5OGVZyPllsJ1fzPKX/T8EwIEn7YsQhqH8sG/HWGm0AdUg3WqEQQrMXAGL1buDjSPKoqOdqenAGFVC7XhSSDz4xSy+ehQf+LSmb34FD7L3maGwHZ3Te8Fmj/kfUmhZ0ZKVxarX4JETHumPJSWXxjyFSBNOtNBYOnVHTldUxYADodzBcBu4D/zqi6dyPj3AE2Pml8qCDoYohlRlZWSkZr/jiHzYkKDCAlLhvGJnIWaHrbF1rKGk1whn1RxV3hfNMwfKSe0Auyj1tQfrjnxBLy2atTUfSZYmY5e6yEemJSXCevhdmdfxIcqr/c1hs3IFqd7AIgujtnL9FXsCSB+qrr1i4mA3yVjlnWRHdyUnp6E1KpvQObZ/YyTnPuQthafQ2sFYytBi+cquwU3T7RMyRxPSc4Cg=

